# Generated by Django 5.2.5 on 2025-09-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('number', models.IntegerField()),
                ('about', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=200)),
                ('optionA', models.CharField(max_length=30)),
                ('optionB', models.CharField(max_length=30)),
                ('optionC', models.CharField(max_length=30)),
                ('optionD', models.CharField(max_length=30)),
                ('correctanswer', models.CharField(max_length=5)),
                ('explanation', models.CharField(max_length=200)),
            ],
        ),
    ]
