# Generated by Django 5.2.5 on 2025-09-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='optionA',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='optionB',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='optionC',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='optionD',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(),
        ),
    ]
